export default function GovernanceBadge({ compact = false }) {
  if (compact) {
    return (
      <span style={{
        display:       'inline-block',
        padding:       '2px 8px',
        background:    '#fee2e2',
        color:         '#991b1b',
        borderRadius:  4,
        fontSize:      '0.7rem',
        fontWeight:    600,
        letterSpacing: '0.02em',
      }}>
        NOT FINANCIAL ADVICE
      </span>
    );
  }

  return (
    <div style={{
      padding:      '0.5rem 0.75rem',
      background:   '#fee2e2',
      border:       '1px solid #fecaca',
      borderRadius: 6,
      fontSize:     '0.8rem',
      color:        '#7f1d1d',
      lineHeight:   1.5,
      margin:       '0.5rem 0',
    }}>
      <strong>Educational analysis only.</strong> This output is generated by AI
      and may be incorrect. Past correlations do not predict future price movements.
      Do not make investment decisions based on this content.
    </div>
  );
}
